version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4510-4559:4510-4559"
      - "4566:4566"
    environment:
      - SERVICES=iam,ec2,dynamodb,s3,lambda,sns,cloudwatch,logs
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./.localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  api:
    build:
      context: ./services
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./services/.env
    depends_on:
      - localstack
    volumes:
      - ./services:/app
      - /app/node_modules